//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public int IdContrato { get; set; }
        public int IdConveniado { get; set; }
        public int IdTipoContrato { get; set; }
    
        public virtual Conveniado Conveniado { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
    }
}
