//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conveniado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conveniado()
        {
            this.Contrato = new HashSet<Contrato>();
            this.Financeiro = new HashSet<Financeiro>();
        }
    
        public int IdConveniado { get; set; }
        public string Descricao { get; set; }
        public int IdEndereco { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public int IdTipoConveniado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financeiro> Financeiro { get; set; }
        public virtual Endereco Endereco { get; set; }
        public virtual TipoConveniado TipoConveniado { get; set; }
    }
}
