//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financeiro
    {
        public int IdFinanceiro { get; set; }
        public int IdConveniado { get; set; }
        public double Valor { get; set; }
        public System.DateTime DataVencimento { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public Nullable<double> ValorPago { get; set; }
    
        public virtual Conveniado Conveniado { get; set; }
    }
}
